version: "3"
services:
  test:
    build: .
    ports:
      - "3055:3055"
    container_name: adapter-arcgis
    environment:
      NODE_ENV: test
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: cttoken
      LOCAL_URL: http://adapter-arcgis.default.svc.cluster.local:3055
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: test
