version: "3"
services:
  test:
    build: .
    ports:
      - "3055:3055"
    container_name: adapter-arcgis
    environment:
      NODE_ENV: test
      CT_URL: http://mymachine:9000
      API_VERSION: v1
      CT_TOKEN: cttoken
      LOCAL_URL: http://adapter-arcgis.default.svc.cluster.local:3055
      FASTLY_ENABLED: "false"
    command: test
